### ISSUE TITLE
Crash when using Sample-APP

### ISSUE THREAD

**Issue by VadymKuriy** [BITalinoWorld/revolution-android-api#3]
Hello,  when try to connect to device I have this crash (Android 6.0.1): 

```
Activity info.plux.pluxapi.sampleapp.DeviceActivity has leaked IntentReceiver info.plux.pluxapi.bitalino.bth.BTHCommunication$1@f00e6eb that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                             android.app.IntentReceiverLeaked: Activity info.plux.pluxapi.sampleapp.DeviceActivity has leaked IntentReceiver info.plux.pluxapi.bitalino.bth.BTHCommunication$1@f00e6eb that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                                 at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1034)
                                                                                 at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:821)
                                                                                 at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1271)
                                                                                 at android.app.ContextImpl.registerReceiver(ContextImpl.java:1251)
                                                                                 at android.app.ContextImpl.registerReceiver(ContextImpl.java:1245)
                                                                                 at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:576)
                                                                                 at info.plux.pluxapi.bitalino.bth.BTHCommunication.init(BTHCommunication.java:162)
                                                                                 at info.plux.pluxapi.bitalino.bth.BTHCommunication.<init>(BTHCommunication.java:152)
                                                                                 at info.plux.pluxapi.bitalino.BITalinoCommunicationFactory.getCommunication(BITalinoCommunicationFactory.java:45)
                                                                                 at info.plux.pluxapi.sampleapp.DeviceActivity.setUIElements(DeviceActivity.java:159)
                                                                                 at info.plux.pluxapi.sampleapp.DeviceActivity.onCreate(DeviceActivity.java:82)
                                                                                 at android.app.Activity.performCreate(Activity.java:6904)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
                                                                                 at android.app.ActivityThread.access$1100(ActivityThread.java:229)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:7325)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by GTelo** [comment]
Hi @VadymKuriy, that issue occurs when you exit the activity without making the connection with the BITalino device. I'll make a commit with that problem solved.

Thank you very much for your input.
